# -*- coding: utf-8 -*-
"""Data_Analysis_Hotel_booking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRJPxZcJHRANKbKJZ9Fj5LBZ3cMRgkpd

/content/drive/MyDrive/Colab Notebooks/hotel_bookings 2.csv
Importing Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""Load the Dataset"""

df = pd.read_csv('hotel_bookings 2.csv')

"""Exploratory Data Analysis & Data Cleaning"""

df.head()

df.info()

df["reservation_status_date"] = pd.to_datetime(df["reservation_status_date"], dayfirst=True)

df.info()

df.describe(include='object')

for col in df.describe(include='object').columns:
  print(col)
  print(df[col].unique())
  print('-'*50)

df.isnull().sum()

df.drop(['company','agent'], axis=1,  inplace=True)
df.dropna(inplace=True)

df.isnull().sum()

df.describe()

df = df[df['adr']<5000]

df.describe()

"""Data Analysis & Visualizations"""

cancelled_perc = df['is_canceled'].value_counts(normalize=True)
print(cancelled_perc)

plt.figure(figsize=(5,4))
plt.title("Reservation Satatus Count")
plt.bar(['Not cancelled','Cancelled'], df['is_canceled'].value_counts(), color="orange")
plt.show()

plt.figure(figsize=(8,4))
ax1 = sns.countplot(x = 'hotel', hue='is_canceled', data = df, palette = 'Oranges')
legend_labels,_ = ax1. get_legend_handles_labels()
ax1.legend(bbox_to_anchor = (1,1))
plt.title("Reservation status in Different Hotels", size=16)
plt.xlabel("Hotel")
plt.ylabel("Number of Reservation")
plt.legend(['Not cancelled','Cancelled'])
plt.show()

resort_hotel = df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel = df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize=(20,8))
plt.title("Average Daily Rate in City & Resort Hotel", size=16)
plt.plot(resort_hotel.index, resort_hotel['adr'], label="Resort Hotel")
plt.plot(city_hotel.index, city_hotel['adr'], label="City Hotel")
plt.legend()
plt.show()

df['month'] = df['reservation_status_date'].dt.month
plt.figure(figsize=(16,8))
ax1 = sns.countplot(x = 'month', hue = 'is_canceled', data = df, palette = 'bright')
legend_labels,_ = ax1. get_legend_handles_labels()
ax1.legend(bbox_to_anchor = (1,1))
plt.title("Reservation status per Month", size=16)
plt.xlabel("Month")
plt.ylabel("Number of Reservation")
plt.legend(['Not cancelled','Cancelled'])
plt.show()

plt.figure(figsize=(15,8))
plt.title("ADR per Month",size=16)
sns.barplot(x='month',y='adr',data = df[df['is_canceled']==1].groupby('month')[['adr']].sum().reset_index())
plt.legend()
plt.show()

cancelled_data = df[df['is_canceled']==1]
top_10_country = cancelled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title("Top 10 Countries in Reservation cancelled")
plt.pie(top_10_country, autopct='%.2f', labels = top_10_country.index)
plt.show()

df['market_segment'].value_counts()

cancelled_data['market_segment'].value_counts(normalize=True)

cancelled_df_adr = cancelled_data.groupby('reservation_status_date')[['adr']].mean()
cancelled_df_adr.reset_index(inplace=True)
cancelled_df_adr.sort_values('reservation_status_date', inplace=True)

non_cancelled_data = df[df['is_canceled']==0]
non_cancelled_df_adr = non_cancelled_data.groupby('reservation_status_date')[['adr']].mean()
non_cancelled_df_adr.reset_index(inplace=True)
non_cancelled_df_adr.sort_values('reservation_status_date', inplace=True)

plt.figure(figsize=(20,8))
plt.title("Average Daily rate")
plt.plot(non_cancelled_df_adr['reservation_status_date'], non_cancelled_df_adr['adr'], label="Not cancelled")
plt.plot(cancelled_df_adr['reservation_status_date'], cancelled_df_adr['adr'], label="Cancelled")
plt.legend()
plt.show()

cancelled_df_adr = cancelled_df_adr[(cancelled_df_adr['reservation_status_date']>'2016') & (cancelled_df_adr['reservation_status_date']<'2017-09')]
non_cancelled_df_adr = non_cancelled_df_adr[(non_cancelled_df_adr['reservation_status_date']>'2016') & (non_cancelled_df_adr['reservation_status_date']<'2017-09')]

plt.figure(figsize=(20,8))
plt.title("Average Daily rate")
plt.plot(non_cancelled_df_adr['reservation_status_date'], non_cancelled_df_adr['adr'], label="Not cancelled")
plt.plot(cancelled_df_adr['reservation_status_date'], cancelled_df_adr['adr'], label="Cancelled")
plt.legend()
plt.show()